enum PreviewMode {
  DETECT_PREVIEW_EDGES_WHITE,
  DETECT_PREVIEW_EDGES_RED,
  DETECT_PREVIEW_EDGES_GREEN,
  DETECT_PREVIEW_EDGES_BLUE,
  DETECT_PREVIEW_EDGES_GRAYSCALE,
  DETECT_PREVIEW_EDGES_WHITE_WITH_BACKGROUND,
  DETECT_EDGES_FAST,
  DETECT_EDGES_FAST_LINES,
};

// Default preview mode
PreviewMode previewMode = PreviewMode::DETECT_PREVIEW_EDGES_WHITE;
PreviewMode previousPreviewMode = previewMode;
